name: Polyquant configured libint build
on:
  push:
    branches:
      - libint

jobs:
  libint-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu_Latest_GCC",
            os: ubuntu-latest,
            artifact: "polyquant-libint.tar.gz",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generators: "Ninja"
          }
    steps:
      - name: checkout project
        uses: actions/checkout@v2
        with:
          ref: 'libint'
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu_Latest_GCC')
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
          sudo apt-get install -y libeigen3-dev
          mkdir builddir
          mkdir installdir
      - name: Configure
        shell: bash
        working-directory: builddir
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DENABLE_FORTRAN=OFF \
            -DLIBINT2_REALTYPE=double \
            -DLIBINT2_BUILD_TESTS=OFF \
            -DLIBINT2_BUILD_SHARED_AND_STATIC_LIBS=ON \
            -G "${{ matrix.config.generators }}" \
            $GITHUB_WORKSPACE
      - name: Build
        shell: bash
        working-directory: builddir
        run: cmake --build . --config ${{ matrix.config.build_type }}
      - name: Build deb
        shell: bash
        working-directory: builddir
        run: cpack -G DEB
      - name: Rename deb
        shell: bash
        run: |
          mv Libint-2.7.0-Linux.deb ${{ matrix.config.artifact }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
